### ISSUE TITLE
Non descriptive errors / unable to fetch any anime

### ISSUE THREAD

**Issue by AzzaDeveloper** [IJPenguin/Penguin-Cli#1]
![image](https://github.com/IJPenguin/Penguin-Cli/assets/25276643/1ebbac22-6ad9-4658-b02c-474a6fa31d61)

Same issue for any anime name attempted.

**Comment by IJPenguin** [comment]
Thanks for the alert, the server was down for the time and i will add descriptive error handling in the next release.

**Comment by IJPenguin** [comment]
The server issue has been fixed
